#!/usr/bin/env bash

if [ $# -eq 0 ]
then
    echo "Error. Must provide username where rbenv should be installed."
    echo "Ex. ./install-rbenv typo3"
    exit 1
fi

executing_user=$(whoami)

if [[ "${executing_user}" != "root" ]]
then
    echo "Error. Must run as root user."
    exit 1
fi

apt-get -y install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev


su - ${1} << EOF
    git clone https://github.com/rbenv/rbenv.git /home/${1}/.rbenv
    cd /home/${1}/.rbenv && src/configure && make -C src
    echo "export PATH=/home/${1}/.rbenv/bin:$PATH" >> /home/${1}/.bash_profile
    echo 'eval "\$(rbenv init -)"' >> /home/${1}/.bash_profile
    git clone https://github.com/rbenv/ruby-build.git /home/${1}/.rbenv/plugins/ruby-build
    /home/${1}/.rbenv/bin/rbenv init
EOF

cat << EOF
Ok, ok, ok it is done

rbenv and ruby-build are setup for: ${1}

Perhaps now you try a little:

rbenv install 2.2.3
rbenv global 2.2.3
rbenv rehash

Also, don't forget:

if \`su ${1}\` is your next course of action then `source ~/.bash_profile `

GOOOOOOOOOOOOOOOOOOD

EOF

exit 0
