#!/usr/bin/env bash
# Author: clark@castironcoding.com
# Purpose: Quick script to the puppet show
# Supported OS: Ubuntu 16.04 LTS; Ubuntu 18.04 LTS

write_puppet_config() {
	cat >/etc/puppetlabs/puppet/puppet.conf <<-EOF
# This file can be used to override the default puppet settings.
# See the following links for more details on what settings are available:
# - https://puppet.com/docs/puppet/latest/config_important_settings.html
# - https://puppet.com/docs/puppet/latest/config_about_settings.html
# - https://puppet.com/docs/puppet/latest/config_file_main.html
# - https://puppet.com/docs/puppet/latest/configuration.html
[agent]
pluginsync      = true
report          = true
ignoreschedules = true
ca_server       = pancho-foreman.cichq.com
server          = pancho-foreman.cichq.com
certname        = `hostname -f`
	EOF
}


setup_puppet6() {
	wget https://apt.puppetlabs.com/puppet6-release-$1.deb
	dpkg -i puppet6-release-$1.deb
	apt-get update
	apt-get install -y puppet-agent
	rm puppet6-release-$1.deb

	write_puppet_config

	chmod +x /etc/profile.d/puppet-agent.sh
	source /etc/profile.d/puppet-agent.sh

	puppet agent --test
}


setup_puppet() {
	if [ ! -r "/etc/lsb-release" ]; then
		echo "Cannot read version" >&2
		exit 1
	fi

	. /etc/lsb-release

	case "$DISTRIB_RELEASE" in
		"16.04")
			setup_puppet6 "xenial"
			;;
		"18.04")
			setup_puppet6 "bionic"
			;;
		"20.04")
			setup_puppet6 "focal"
			;;
		*)
			echo "Unknown version: ${DISTRIB_RELEASE}" >&2
			exit 1
			;;
	esac
}

setup_puppet
