#!/bin/bash
# Author: clark@castironcoding.com
# Purpose: Quick script to the puppet show
# Supported OS: Ubuntu 16.04 LTS 

apt-get update
apt-get install -y puppet
echo $'[main]\nvardir = /var/lib/puppet\nlogdir = /var/log/puppet\nrundir = /var/run/puppet\nssldir = $vardir/ssl\n\n[agent]\npluginsync = true\nreport = true\nignoreschedules = true\nca_server = pancho.cichq.com\ncertname = '${HOSTNAME}$'\nenvironment = production\nserver = pancho-puppet.cichq.com\n' > /etc/puppet/puppet.conf
puppet agent --test

exit 0
